# Generated by Django 5.1.2 on 2024-11-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customeuser_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
