# Generated by Django 5.1.2 on 2024-11-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authentication', '0004_remove_customeuser_groups_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='CustomUser',
        ),
    ]
