# Generated by Django 5.1.3 on 2024-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.CharField(blank=True, help_text='Comma-separated values of selected options', max_length=200)),
            ],
        ),
    ]
