# Generated by Django 5.1.3 on 2024-12-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='selected_options_1',
            field=models.CharField(blank=True, help_text='Comma-separated values for selected options 1', max_length=200),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='selected_options_2',
            field=models.CharField(blank=True, help_text='Comma-separated values for selected options 2', max_length=200),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='selected_options_3',
            field=models.CharField(blank=True, help_text='Comma-separated values for selected options 3', max_length=200),
        ),
    ]
