# Generated by Django 5.1.4 on 2024-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userpreferences_selected_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_options_1',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_options_2',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_options_3',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='food',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hotel',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='park',
            field=models.JSONField(default=list),
        ),
    ]
