# Generated by Django 5.1.4 on 2024-12-19 14:24

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userpreferences_selected_options_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='food',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Sushi', 'Sushi'), ('Pasta', 'Pasta'), ('Salad', 'Salad')], max_length=400),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='hotel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Five Star', 'Five Star'), ('Budget Friendly', 'Budget Friendly'), ('Family Friendly', 'Family Friendly'), ('Fast Food', 'Fast Food'), ('Fine Dining', 'Fine Dining')], max_length=500),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='park',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure Park', 'Adventure Park'), ('Water Park', 'Water Park'), ('Amusement Park', 'Amusement Park'), ('National Park', 'National Park'), ('City Park', 'City Park')], max_length=500),
        ),
    ]
