# Generated by Django 5.1.4 on 2024-12-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_userprofile_userprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='about',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=800),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionCategory',
        ),
    ]
