# Generated by Django 5.1.4 on 2025-01-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userinfotemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotemp',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
