# Generated by Django 5.1.4 on 2025-01-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_bucket_experience_delete_userinfotemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucket',
            new_name='MessageBucket',
        ),
    ]
