# Generated by Django 5.1.4 on 2025-01-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_bucket_messagebucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
