# Generated by Django 5.1.4 on 2025-01-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_experience_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='bucket',
            new_name='user',
        ),
    ]
