# Generated by Django 5.1.4 on 2025-01-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_bucket_experience_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageBucket',
        ),
    ]
