# Generated by Django 5.1.3 on 2024-11-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsocket',
            name='is_availble',
            field=models.BooleanField(default=True),
        ),
    ]
