# Generated by Django 5.1.2 on 2024-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('full_address', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
