# Generated by Django 5.1.2 on 2024-11-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiledata', '0003_remove_userdata_age_userdata_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_types', models.JSONField(default=list)),
                ('ambiance_preferences', models.JSONField(default=list)),
                ('favorite_music_genres', models.JSONField(default=list)),
                ('event_interests', models.JSONField(default=list)),
                ('pre_event_activities', models.JSONField(default=list)),
                ('dietary_preferences', models.JSONField(default=list)),
                ('drink_preferences', models.JSONField(default=list)),
                ('social_vibe', models.JSONField(default=list)),
                ('decor_preferences', models.JSONField(default=list)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('meetup_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='userprofiledata.userdata')),
            ],
        ),
    ]
