# Generated by Django 5.1.2 on 2024-11-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiledata', '0004_userpreference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreference',
            new_name='UserPreferences',
        ),
    ]
